version: '3.3'
services:
  nginx:
    build: ./nginx
    volumes:
      - ./public:/usr/share/nginx/html/public
    ports:
      - '80:80'
      - '443:443'
  mongo:
    image: mongo:4.2.5
    ports:
      - '27017:27017'
  app:
    build: .
    volumes:
      - ./public:/root/public
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - '8080:8080'